server:
  port: 8091
  servlet.contextPath: /integrator

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:bank_integration.db
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        order_inserts: true
        generate_statistics: false
        jdbc:
          batch_size: 20
  mail:
    host: smtp.gmail.com
    port: 587
    username: hosurveeresh@gmail.com
    password: cswu cvbd iuho hlhs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging.level.com.lbg.data.migration.feign.DataSourceHttpClient: DEBUG
